#!/bin/sh
#          _           _           _
#  ___ _ _| |_ ___ ___| |_ ___ ___| |_
# | .'| | |  _| . |_ -|  _| .'|  _|  _|
# |__,|___|_| |___|___|_| |__,|_| |_|

###load and export variables
xrandr
xrdb -merge -I$HOME ~/.Xresources
[[ -f ~/.Xdefaults ]] && xrdb -merge ~/.Xdefaults

[[ -f ~/.zshenv ]] && source ~/.zshenv
[[ -f ~/.zprofile ]] && source ~/.zprofile

xsetroot -cursor_name left_ptr &
export MICRO_TRUECOLOR=1

setxkbmap -option "caps:swapescape" &

if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

if [ -x /usr/bin/xdg-user-dirs-update ]; then
   /usr/bin/xdg-user-dirs-update
fi

export MICRO_TRUECOLOR=1

#Find out your monitor name with xrandr or arandr (save and you get this line)
#xrandr --output VGA-1 --primary --mode 1360x768 --pos 0x0 --rotate normal
#xrandr --output DP2 --primary --mode 1920x1080 --rate 60.00 --output LVDS1 --off &
#xrandr --output LVDS1 --mode 1366x768 --output DP3 --mode 1920x1080 --right-of LVDS1
#xrandr --output HDMI0 --mode 1920x1080 --pos 0x0 --rotate normal --output
#xrandr --output DP2 --mode 2560x1440 --pos 1920x0 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off
nvidia-settings -l
##
###load bar and wallpaper
$HOME/bin/bspbar.sh

if pgrep -af variety > /dev/null
then
	echo "Variety is running"
else
	variety &
fi
##Kill any currently running tint2
killall tint2
## UI Appearance - Open Last Theme (wallpaper, panel, notify-daemon)
#current="$(cat ~/.config/openbox/visual-mode/current)"
#bash ~/.config/openbox/visual-mode/$current/ui

# Lauch notification daemon
~/bin/bspdunst.sh

# Lauch compositor
~/bin/bspcomp.sh

#change your keyboard if you need it
#setxkbmap -layout be

#Some ways to set your wallpaper besides variety or nitrogen
#feh --bg-scale ~/.config/bspwm/wall.png &
# -R restores the last colorscheme that was in use and -o runs the script to set 2bwm theme
#wal -R -o wal-set &

###Kill daemons and programs
#killall clipit &
killall volumeicon &
###Start daemons and programs
skippy-xd --start-daemon &
nm-applet &
numlockx on &
#blueberry-tray &
#urxvtd &
#clipit &
mpd &
volumeicon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/usr/lib/xfce4/notifyd/xfce4-notifyd &
xfsettingsd &
sleep 1; thunar --daemon &

###load arandr config at startup
#sleep 3; ~/.screenlayout/default.sh
