#! /bin/sh

###load and export variables
source "$HOME/.cache/wal/colors.sh"

xrdb -I$HOME ~/.Xresources
[[ -f ~/.Xdefaults ]] && xrdb -merge ~/.Xdefaults

if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
if [ -x /usr/bin/xdg-user-dirs-update ]; then
   /usr/bin/xdg-user-dirs-update
fi

export MICRO_TRUECOLOR=1

xsetroot -cursor_name left_ptr &

###load arandr config at startsup
sleep 3; ~/.screenlayout/default.sh

###load keybindings
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
sxhkd -c $HOME/.config/sxhkd/common-keys &

###set gaps and colours
bspc config border_width        2
bspc config window_gap         16

bspc config normal_border_color "$color0"
bspc config focused_border_color "$color4"
bspc config active_border_color "$color8"
bspc config presel_border_color "$color5"
bspc config focused_locked_border_color "$color1"
bspc config active_locked_border_color "$color1"
bspc config normal_locked_border_color "$color1"
bspc config focused_sticky_border_color "$color1"
bspc config active_sticky_border_color "$color3"
bspc config normal_sticky_border_color "$color3"
bspc config focused_private_border_color "$color3"
bspc config active_private_border_color "$color3"
bspc config normal_private_border_color "$color3"
bspc config urgent_border_color "$color5"

bspc config split_ratio         0.62
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

###set workspaces per monitor
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

#Floating applications
bspc rule -a arandr state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating center=true
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
bspc rule -a Xfce4-appfinder state=floating sticky=on

bspc rule -a screenkey --unmanage
bspc rule -a gcolor2 state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a gmrun state=floating center=true
bspc rule -a lxterminal state=floating center=true sticky=true
#bspc rule -a urxvt state=floating center=true
bspc rule -a viewnior state=floating center=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a spotify state=pseudo_tiled
#bspc rule -a nautilus state=pseudo_tiled
bspc rule -a skype state=pseudo_tiled
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a yad state=floating
bspc rule -a Docky layer=above border=off manage=on
bspc rule -a Plank layer=above border=off manage=on
bspc rule -a wbar layer=above
bspc rule -a dockbarx layer=above
bspc rule -a google-chrome-stable private=on
bspc rule -a chromium private=on
bspc rule -a vivaldi-stable private=on
bspc rule -a firefox private=on
bspc rule -a gnome-pie border=off manage=off
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a 9menu border=off manage=off
bspc rule -a tint2 border=off manage=off
bspc rule -a trayer border=off manage=off layer=above
bspc rule -a xmobar border=off manage=off layer=above
bspc rule -a dzen2 border=off manage=off layer=above

###load polybar and wallpaper
##$HOME/.config/polybar/launch.sh &
## UI Appearance - Open Last Theme (wallpaper, panel, notify-daemon)
current="$(cat ~/.config/openbox/visual-mode/current)"
bash ~/.config/openbox/visual-mode/$current/ui
